$info_challenge = Invoke-RestMethod -Method Get -Uri 'https://si-interview-api.azurewebsites.net/api/Information/Challenge'
$weather_forecast_get = Invoke-RestMethod -Method Get -Uri 'https://si-interview-api.azurewebsites.net/api/WeatherForecast/WeatherForecast'
$weather_forecast_post = Invoke-RestMethod -Method Post -Uri 'https://si-interview-api.azurewebsites.net/api/WeatherForecast/WeatherForecast'
$weather_forecast_put =  Invoke-RestMethod -Method Put -Uri 'https://si-interview-api.azurewebsites.net/api/WeatherForecast/WeatherForecast'
$weather_forecast_location = Invoke-RestMethod -Method Get -Uri 'https://si-interview-api.azurewebsites.net/api/WeatherForecast/WeatherForecast/salt%20lake%20city'
$weather_forecast_delete = Invoke-RestMethod -Method Delete -Uri 'https://si-interview-api.azurewebsites.net/api/WeatherForecast/WeatherForecast/1234'